=== miguelvieira123/GAMu/editor_gramatica/GAMu/validacoes_xml/alunos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="alunos">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="aluno">
                    <xs:complexType mixed="false">
                        <xs:sequence>
                            <xs:element name="cursos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="curso">
                                            <xs:complexType>
                                                <xs:attribute name="id"/>
                                                <xs:attribute name="id_instrumento"/>
                                                <xs:attribute name="anoLetivo"/>
                                                <xs:attribute name="anoCurso"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="instrumentos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="instrumento">
                                            <xs:complexType>
                                                <xs:attribute name="id"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id"/>
                        <xs:attribute name="nome"/>
                        <xs:attribute name="dataNsc"/>
                        <xs:attribute name="mail"/>
                        <xs:attribute name="telemovel"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== miguelvieira123/GAMu/editor_gramatica/GAMu/validacoes_xml/Alunos.xml
<?xml version="1.0"?>
<alunos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="file:/C:/xampp/htdocs/GAMu/alunos.xsd">

	<aluno id="A11122" nome="Maria11 Luisa Villaverde Machado Fernandes Novais" dataNsc="2004-04-01" mail="" telemovel="">
		<cursos>
			<curso id="CS13" id_instrumento="I13" anoLetivo="2015/2016" anoCurso="2"/>
			<curso id="CB6" id_instrumento="I6" anoLetivo="2015/2016" anoCurso="2"/>
		</cursos>
		<instrumentos>
			<instrumento id="I13"/>
			<instrumento id="I6"/>
		</instrumentos>
	</aluno>
	<aluno id="A11133" nome="Ademar22 Fontes De Magalhaes Goncalves" dataNsc="2002-07-08" mail="" telemovel="">
		<cursos>
			<curso id="CB6" id_instrumento="I6" anoLetivo="2015/2016" anoCurso="2"/>
			<curso id="CS13" id_instrumento="I13" anoLetivo="2015/2016" anoCurso="2"/>
		</cursos>
		<instrumentos>
			<instrumento id="I6"/>
			<instrumento id="I13"/>
		</instrumentos>
	</aluno>
</alunos>
