=== miguelvieira123/GAMu/editor_gramatica/GAMu/validacoes_xml/professores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="professores">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="professor">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cursos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" name="curso">
                                            <xs:complexType>
                                                <xs:attribute name="id"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id"/>
                        <xs:attribute name="nome"/>
                        <xs:attribute name="dataNsc"/>
                        <xs:attribute name="mail"/>
                        <xs:attribute name="telemovel"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== miguelvieira123/GAMu/editor_gramatica/GAMu/validacoes_xml/Professores.xml
<?xml version="1.0"?>
<professores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:/C:/xampp/htdocs/GAMu/professores.xsd">

	<professor id="P1" nome="Alvaro Jose De Castro Moreira Da Silva" dataNsc="1963-08-27" mail="P1@gamu.pt" telemovel="+351934534235">
		<cursos>
			<curso id="CS20"/>
		</cursos>
	</professor>
	<professor id="P10" nome="Pedro Manuel Vieira Santos Pinto" dataNsc="1956-11-13" mail="" telemovel="">
		<cursos>
			<curso id="CS3"/>
		</cursos>
	</professor>
	<professor id="P11" nome="Rui Manuel Afonso Rodrigues Silva Guerra" dataNsc="1967-10-13" mail="" telemovel="">
		<cursos>
			<curso id="CB15"/>
		</cursos>
	</professor>
	<professor id="P12" nome="Sergio Miguel Valente De Almeida" dataNsc="1954-06-28" mail="" telemovel="">
		<cursos>
			<curso id="CS18"/>
		</cursos>
	</professor>
	<professor id="P13" nome="Tiago Machado Silva" dataNsc="1946-08-21" mail="" telemovel="">
		<cursos>
			<curso id="CB15"/>
		</cursos>
	</professor>
	<professor id="P14" nome="Vasco Duarte Almeida Dias De Castro" dataNsc="1947-10-04" mail="" telemovel="">
		<cursos>
			<curso id="CS21"/>
		</cursos>
	</professor>
	<professor id="P15" nome="Antonio Jose Oliveira Faria" dataNsc="1946-12-21" mail="" telemovel="">
		<cursos>
			<curso id="CB19"/>
		</cursos>
	</professor>
	<professor id="P16" nome="Carla Maria Mendes De Castro" dataNsc="1953-01-27" mail="" telemovel="">
		<cursos>
			<curso id="CS11"/>
		</cursos>
	</professor>
	<professor id="P17" nome="Marlene Azevedo Da Silva" dataNsc="1954-06-11" mail="" telemovel="">
		<cursos>
			<curso id="CB20"/>
		</cursos>
	</professor>
	<professor id="P18" nome="Paulo Alexandre Marques De Oliveira Serafim" dataNsc="1961-11-20" mail="" telemovel="">
		<cursos>
			<curso id="CB21"/>
		</cursos>
	</professor>
	<professor id="P19" nome="David Filipe Oliveira Costa" dataNsc="1959-10-01" mail="" telemovel="">
		<cursos>
			<curso id="CS19"/>
		</cursos>
	</professor>
	<professor id="P2" nome="Andre Filipe Azevedo Sousa" dataNsc="1968-03-15" mail="" telemovel="">
		<cursos>
			<curso id="CB9"/>
		</cursos>
	</professor>
	<professor id="P20" nome="Ricardo Miguel Carvalho Ferreira" dataNsc="1950-06-21" mail="" telemovel="">
		<cursos>
			<curso id="CS11"/>
		</cursos>
	</professor>
	<professor id="P21" nome="Jose Alves De Castro" dataNsc="1973-09-16" mail="" telemovel="">
		<cursos>
			<curso id="CB17"/>
		</cursos>
	</professor>
	<professor id="P22" nome="Mario Bento Brito Nobrega Ramos De Azevedo" dataNsc="1969-03-06" mail="" telemovel="">
		<cursos>
			<curso id="CS16"/>
		</cursos>
	</professor>
	<professor id="P23" nome="Paulo Cesar Rodrigues Gomes" dataNsc="1949-08-26" mail="" telemovel="">
		<cursos>
			<curso id="CS7"/>
		</cursos>
	</professor>
	<professor id="P24" nome="Susana Pereira" dataNsc="1989-08-23" mail="" telemovel="">
		<cursos>
			<curso id="CS13"/>
		</cursos>
	</professor>
	<professor id="P25" nome="Gabriel Reis" dataNsc="1980-09-04" mail="" telemovel="">
		<cursos>
			<curso id="CB13"/>
		</cursos>
	</professor>
	<professor id="P26" nome="Ars&#xC3;&#xA9;nio" dataNsc="1973-03-05" mail="" telemovel="">
		<cursos>
			<curso id="CB17"/>
		</cursos>
	</professor>
	<professor id="P27" nome="Frederico Pinto" dataNsc="1988-01-07" mail="" telemovel="">
		<cursos>
			<curso id="CB7"/>
		</cursos>
	</professor>
	<professor id="P28" nome="Gon&#xC3;&#xA7;alo Hermenegildo" dataNsc="1965-02-28" mail="" telemovel="">
		<cursos>
			<curso id="CS6"/>
		</cursos>
	</professor>
	<professor id="P29" nome="Luis" dataNsc="1987-03-26" mail="" telemovel="">
		<cursos>
			<curso id="CB4"/>
		</cursos>
	</professor>
	<professor id="P3" nome="Bruno Miguel Pereira Pinto" dataNsc="1977-05-06" mail="" telemovel="">
		<cursos>
			<curso id="CB4"/>
		</cursos>
	</professor>
	<professor id="P30" nome="Miguel Pinto" dataNsc="1977-01-02" mail="" telemovel="">
		<cursos>
			<curso id="CB19"/>
		</cursos>
	</professor>
	<professor id="P31" nome="Pedro Lopes" dataNsc="1979-06-09" mail="" telemovel="">
		<cursos>
			<curso id="CB1"/>
		</cursos>
	</professor>
	<professor id="P32" nome="Ant&#xC3;&#xB3;nio Jos&#xC3;&#xA9; Coutinho Barbosa" dataNsc="1969-05-11" mail="" telemovel="">
		<cursos>
			<curso id="CB7"/>
		</cursos>
	</professor>
	<professor id="P33" nome="Ricardo Paz" dataNsc="1966-06-21" mail="" telemovel="">
		<cursos>
			<curso id="CS21"/>
		</cursos>
	</professor>
	<professor id="P34" nome="Sandrina Maciel" dataNsc="1980-11-04" mail="" telemovel="">
		<cursos>
			<curso id="CB18"/>
		</cursos>
	</professor>
	<professor id="P35" nome="Bruno Martins" dataNsc="1962-04-19" mail="" telemovel="">
		<cursos>
			<curso id="CB17"/>
		</cursos>
	</professor>
	<professor id="P36" nome="Filipe Froufe" dataNsc="1960-07-22" mail="" telemovel="">
		<cursos>
			<curso id="CB9"/>
		</cursos>
	</professor>
	<professor id="P37" nome="Jo&#xC3;&#xA3;o Brites" dataNsc="1950-09-21" mail="" telemovel="">
		<cursos>
			<curso id="CS1"/>
		</cursos>
	</professor>
	<professor id="P38" nome="Leandro Morgado" dataNsc="1952-07-14" mail="" telemovel="">
		<cursos>
			<curso id="CB22"/>
		</cursos>
	</professor>
	<professor id="P39" nome="Manuel Sousa" dataNsc="1992-03-21" mail="" telemovel="">
		<cursos>
			<curso id="CB3"/>
		</cursos>
	</professor>
	<professor id="P4" nome="Filipe Alexandre Da Silva Martins" dataNsc="1988-12-10" mail="" telemovel="">
		<cursos>
			<curso id="CB19"/>
		</cursos>
	</professor>
	<professor id="P40" nome="Pedro Resende" dataNsc="1983-03-24" mail="" telemovel="">
		<cursos>
			<curso id="CB13"/>
		</cursos>
	</professor>
	<professor id="P41" nome="Ricardo" dataNsc="1955-02-24" mail="" telemovel="">
		<cursos>
			<curso id="CS15"/>
		</cursos>
	</professor>
	<professor id="P42" nome="Fernanda Barroso" dataNsc="1954-01-03" mail="" telemovel="">
		<cursos>
			<curso id="CB18"/>
		</cursos>
	</professor>
	<professor id="P43" nome="Marta Silva" dataNsc="1985-06-01" mail="" telemovel="">
		<cursos>
			<curso id="CS22"/>
		</cursos>
	</professor>
	<professor id="P44" nome="Paulo Alexandre Afonso Dias" dataNsc="1966-12-15" mail="" telemovel="">
		<cursos>
			<curso id="CB16"/>
		</cursos>
	</professor>
	<professor id="P45" nome="Susana Pacheco" dataNsc="1982-02-06" mail="" telemovel="">
		<cursos>
			<curso id="CB22"/>
		</cursos>
	</professor>
	<professor id="P46" nome="Almeno" dataNsc="1982-08-02" mail="" telemovel="">
		<cursos>
			<curso id="CS16"/>
		</cursos>
	</professor>
	<professor id="P47" nome="Carlos Durana" dataNsc="1970-05-14" mail="" telemovel="">
		<cursos>
			<curso id="CS10"/>
		</cursos>
	</professor>
	<professor id="P48" nome="Hernani Silva" dataNsc="1945-03-13" mail="" telemovel="">
		<cursos>
			<curso id="CS8"/>
		</cursos>
	</professor>
	<professor id="P49" nome="Sofia Paiva" dataNsc="1965-06-22" mail="" telemovel="">
		<cursos>
			<curso id="CB9"/>
		</cursos>
	</professor>
	<professor id="P5" nome="Helder Ricardo Dias Ribeiro" dataNsc="1969-03-04" mail="" telemovel="">
		<cursos>
			<curso id="CS15"/>
		</cursos>
	</professor>
	<professor id="P50" nome="Bruno Miguel Pereira Pinto" dataNsc="1971-01-20" mail="" telemovel="">
		<cursos>
			<curso id="CB5"/>
		</cursos>
	</professor>
	<professor id="P51" nome="Cristiano Cunha" dataNsc="1987-05-06" mail="" telemovel="">
		<cursos>
			<curso id="CB21"/>
		</cursos>
	</professor>
	<professor id="P52" nome="Daniel Pires" dataNsc="1976-08-05" mail="" telemovel="">
		<cursos>
			<curso id="CB1"/>
		</cursos>
	</professor>
	<professor id="P53" nome="Ernesto Miranda Pedrosa Da Silva" dataNsc="1977-11-13" mail="" telemovel="">
		<cursos>
			<curso id="CB20"/>
		</cursos>
	</professor>
	<professor id="P54" nome="Manuel Joao Salgado Da Costa Amaro" dataNsc="1977-09-11" mail="" telemovel="">
		<cursos>
			<curso id="CS3"/>
		</cursos>
	</professor>
	<professor id="P55" nome="Pedro Nuno Tavares Da Silva " dataNsc="1978-12-06" mail="" telemovel="">
		<cursos>
			<curso id="CB12"/>
		</cursos>
	</professor>
	<professor id="P56" nome="Rui Pedro Da Costa Barbosa" dataNsc="1977-11-14" mail="" telemovel="">
		<cursos>
			<curso id="CS5"/>
		</cursos>
	</professor>
	<professor id="P57" nome="Carlos Guilherme Pelaio Macedo Costa " dataNsc="1955-03-28" mail="" telemovel="">
		<cursos>
			<curso id="CB19"/>
		</cursos>
	</professor>
	<professor id="P58" nome="Jorge Filipe Marcos Mota " dataNsc="1947-10-23" mail="" telemovel="">
		<cursos>
			<curso id="CS2"/>
		</cursos>
	</professor>
	<professor id="P59" nome="Nuno Miguel Alves Peixoto" dataNsc="1986-12-22" mail="" telemovel="">
		<cursos>
			<curso id="CB20"/>
		</cursos>
	</professor>
	<professor id="P6" nome="Hernani Rodrigues Da Silva" dataNsc="1971-11-21" mail="" telemovel="">
		<cursos>
			<curso id="CB7"/>
		</cursos>
	</professor>
	<professor id="P60" nome="V&#xC3;&#xA2;nia Sifia Carvalho" dataNsc="1986-01-17" mail="" telemovel="">
		<cursos>
			<curso id="CS5"/>
		</cursos>
	</professor>
	<professor id="P61" nome="Maria Campos" dataNsc="1963-06-07" mail="" telemovel="">
		<cursos>
			<curso id="CB21"/>
		</cursos>
	</professor>
	<professor id="P62" nome="Nuno Rodrigues" dataNsc="1983-06-17" mail="" telemovel="">
		<cursos>
			<curso id="CB15"/>
		</cursos>
	</professor>
	<professor id="P63" nome="Ad&#xC3;&#xA9;lio Marco Da Costa Fernandes" dataNsc="1972-11-13" mail="" telemovel="">
		<cursos>
			<curso id="CB22"/>
		</cursos>
	</professor>
	<professor id="P64" nome="Alexandre Gon&#xC3;&#xA7;alves" dataNsc="1970-12-16" mail="" telemovel="">
		<cursos>
			<curso id="CB18"/>
		</cursos>
	</professor>
	<professor id="P65" nome="Am&#xC3;&#xA2;ndio Telmo Oliveira Teixeira" dataNsc="1961-12-11" mail="" telemovel="">
		<cursos>
			<curso id="CB22"/>
		</cursos>
	</professor>
	<professor id="P66" nome="Carla Sofia De Almeida Coutinho " dataNsc="1989-01-06" mail="" telemovel="">
		<cursos>
			<curso id="CB10"/>
		</cursos>
	</professor>
	<professor id="P67" nome="Edison Oliveira" dataNsc="1974-09-19" mail="" telemovel="">
		<cursos>
