=== miguelvieira123/GAMu/relatorio/report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="relatorio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="capa">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="autores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="autor">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="nome" type="xs:string"/>
                                                  <xs:element name="instituicao" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="instituicao" type="xs:string"/>
                            <xs:element name="data" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="resumo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="texto" type="xs:string"/>
                            <xs:element maxOccurs="unbounded" name="keywords" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="indice" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="refindice">
                                <xs:complexType mixed="true">
                                    <xs:attribute name="ref" type="xs:IDREF"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lista_figuras" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="reffigura">
                                <xs:complexType mixed="true">
                                    <xs:attribute name="ref" type="xs:IDREF"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="lista_tabelas" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="reftabela">
                                <xs:complexType mixed="true">
                                    <xs:attribute name="ref" type="xs:IDREF"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="introducao">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="p"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="capitulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="capitulo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element maxOccurs="unbounded" ref="p"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="seccao">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="titulo" type="xs:string"/>
                                                  <xs:element maxOccurs="unbounded" ref="p"/>
                                                  <xs:element maxOccurs="unbounded" minOccurs="0"
                                                  name="subseccao">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="titulo" type="xs:string"/>
                                                  <xs:element maxOccurs="unbounded" ref="p"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="id" type="xs:ID"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:ID"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="conclusao">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="p"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="anexos" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="anexo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" ref="p"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" ref="figura"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0" ref="tabela"
                                        />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="referencias" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="referencia">
                                <xs:complexType mixed="true">
                                    <xs:attribute name="url" type="xs:anyURI"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="p">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="b" type="xs:string"/>
                <xs:element name="i" type="xs:string"/>
                <xs:element name="u" type="xs:string"/>
                <xs:element ref="figura"/>
                <xs:element ref="tabela"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="figura">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="legenda" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="tabela">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="tr">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="td" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== miguelvieira123/GAMu/relatorio/relatorio.xml
<?xml version="1.0" encoding="UTF-8"?>
<relatorio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/xampp/htdocs/GAMu/relatorio/report.xsd">
    <capa>
        <titulo>Relatório Trabalho Prático 1</titulo>
        <autores>
            <autor>
                <nome>Luís Miguel Fernandes Vieira</nome>
                <instituicao>Universidade do Minho</instituicao>
            </autor>
            <autor>
                <nome>Oleskii Gylytskyy</nome>
                <instituicao>Universidade do Minho</instituicao>
            </autor>
        </autores>
        <instituicao>Universidade do Minho</instituicao>
        <data>18/01/2016</data>
    </capa>
    <resumo>
        <texto>texto0</texto>
        <keywords>keywords0</keywords>
        <keywords>keywords1</keywords>
    </resumo>
    <introducao>
        <p>
            <b>b0</b>
            <i>i0</i>
            <u>u0</u>
            <figura>
                <legenda>legenda0</legenda>
            </figura>
            <tabela>
                <tr>
                    <td>td0</td>
                    <td>td1</td>
                </tr>
                <tr>
                    <td>td2</td>
                    <td>td3</td>
                </tr>
            </tabela>
        </p>
        <p>
            <b>b1</b>
            <i>i1</i>
            <u>u1</u>
            <figura>
                <legenda>legenda1</legenda>
            </figura>
            <tabela>
                <tr>
                    <td>td4</td>
                    <td>td5</td>
                </tr>
                <tr>
                    <td>td6</td>
                    <td>td7</td>
                </tr>
            </tabela>
        </p>
    </introducao>
    <capitulos>
        <capitulo>
            <titulo>titulo1</titulo>
            <p>
                <b>b2</b>
                <i>i2</i>
                <u>u2</u>
                <figura>
                    <legenda>legenda2</legenda>
                </figura>
                <tabela>
                    <tr>
                        <td>td8</td>
                        <td>td9</td>
                    </tr>
                    <tr>
                        <td>td10</td>
                        <td>td11</td>
                    </tr>
                </tabela>
            </p>
            <p>
                <b>b3</b>
                <i>i3</i>
                <u>u3</u>
                <figura>
                    <legenda>legenda3</legenda>
                </figura>
                <tabela>
                    <tr>
                        <td>td12</td>
                        <td>td13</td>
                    </tr>
                    <tr>
                        <td>td14</td>
                        <td>td15</td>
                    </tr>
                </tabela>
            </p>
        </capitulo>
        <capitulo>
            <titulo>titulo2</titulo>
            <p>
                <b>b4</b>
                <i>i4</i>
                <u>u4</u>
                <figura>
                    <legenda>legenda4</legenda>
                </figura>
                <tabela>
                    <tr>
                        <td>td16</td>
                        <td>td17</td>
                    </tr>
                    <tr>
                        <td>td18</td>
                        <td>td19</td>
                    </tr>
                </tabela>
            </p>
            <p>
                <b>b5</b>
                <i>i5</i>
                <u>u5</u>
                <figura>
                    <legenda>legenda5</legenda>
                </figura>
                <tabela>
                    <tr>
                        <td>td20</td>
                        <td>td21</td>
                    </tr>
                    <tr>
                        <td>td22</td>
                        <td>td23</td>
                    </tr>
                </tabela>
            </p>
        </capitulo>
    </capitulos>
    <conclusao>
        <p>
            <b>b6</b>
            <i>i6</i>
            <u>u6</u>
            <figura>
                <legenda>legenda6</legenda>
            </figura>
            <tabela>
                <tr>
                    <td>td24</td>
                    <td>td25</td>
                </tr>
                <tr>
                    <td>td26</td>
                    <td>td27</td>
                </tr>
            </tabela>
        </p>
        <p>
            <b>b7</b>
            <i>i7</i>
            <u>u7</u>
            <figura>
                <legenda>legenda7</legenda>
            </figura>
            <tabela>
                <tr>
                    <td>td28</td>
                    <td>td29</td>
                </tr>
                <tr>
                    <td>td30</td>
                    <td>td31</td>
                </tr>
            </tabela>
        </p>
    </conclusao>
</relatorio>
