=== miguelvieira123/GAMu/site/schemas/audicoes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="audicoes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="audicao" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="metainfo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" name="subtitulo" type="xs:string"/>
                                        <xs:element minOccurs="0" name="tema" type="xs:string"/>
                                        <xs:element name="data" type="xs:string"/>
                                        <xs:element name="hora" type="xs:string"/>
                                        <xs:element name="local" type="xs:string"/>
                                        <xs:element name="organizador">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="id"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="duracao" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="atuacoes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="atuacao" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element minOccurs="0" name="nome_grupo"
                                                  type="xs:string"/>
                                                  <xs:element name="hora_inicio" type="xs:string"/>
                                                  <xs:element name="musicos">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="musico" maxOccurs="unbounded">
                                                  <xs:complexType mixed="true">
                                                  <xs:sequence>
                                                  <xs:element name="nome" type="xs:string"/>
                                                  <xs:element name="instrumento">
                                                  <xs:complexType>
                                                  <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="id"/>
                                                  </xs:extension>
                                                  </xs:simpleContent>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  <xs:attribute name="id"/>
                                                  <xs:attribute name="tipo"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="obras">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="obra">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="nome" type="xs:string"/>
                                                  <xs:element name="duracao" type="xs:string"/>
                                                  </xs:sequence>
                                                  <xs:attribute name="id"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="tipo"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== miguelvieira123/GAMu/editor_gramatica/GAMu/audiiiiiiii1.xml
<?xml version="1.0" encoding="UTF-8"?>
<audicoes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/xampp/htdocs/GAMu/audicoes.xsd">
    <audicao id="id0">
        <metainfo>
            <data>data0</data>
            <hora>hora0</hora>
            <local>local0</local>
            <organizador>organizador0</organizador>
            <duracao>duracao0</duracao>
        </metainfo>
        <atuacoes>
            <atuacao>
                <hora_inicio>hora_inicio0</hora_inicio>
                <musicos>
                    <musico>
                        <nome>nome0</nome>
                        <instrumento>instrumento0</instrumento>
                    </musico>
                    <musico>
                        <nome>nome1</nome>
                        <instrumento>instrumento1</instrumento>
                    </musico>
                </musicos>
                <obras>
                    <obra>
                        <nome>nome2</nome>
                        <duracao>duracao1</duracao>
                    </obra>
                    <obra>
                        <nome>nome3</nome>
                        <duracao>duracao2</duracao>
                    </obra>
                </obras>
            </atuacao>
            <atuacao>
                <hora_inicio>hora_inicio1</hora_inicio>
                <musicos>
                    <musico>
                        <nome>nome4</nome>
                        <instrumento>instrumento2</instrumento>
                    </musico>
                    <musico>
                        <nome>nome5</nome>
                        <instrumento>instrumento3</instrumento>
                    </musico>
                </musicos>
                <obras>
                    <obra>
                        <nome>nome6</nome>
                        <duracao>duracao3</duracao>
                    </obra>
                    <obra>
                        <nome>nome7</nome>
                        <duracao>duracao4</duracao>
                    </obra>
                </obras>
            </atuacao>
        </atuacoes>
    </audicao>
</audicoes>

=== miguelvieira123/GAMu/editor_gramatica/GAMu/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<audicoes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/xampp/htdocs/GAMu/audicoes.xsd">
    <audicao>
        <metainfo>
            <titulo>titulo0</titulo>
            <subtitulo>subtitulo</subtitulo>
            <tema>tema da audicao</tema>
            <data>22/01/2016</data>
            <hora_inicio>12:30</hora_inicio>
            <hora_fim>14:30</hora_fim>
            <local>local0</local>
            <organizador>P1</organizador>
            <duracao>2:00</duracao>
        </metainfo>
        <atuacoes>
            <atuacao tipo="grupo">
                <nome_grupo>nome do grupo musical</nome_grupo>
                <hora_inicio>12:30</hora_inicio>
                <obras>
                    <obra id="O1">
                        <nome>nome0</nome>
                        <duracao>0:20</duracao>
                    </obra>
                    <obra id="O23">
                        <nome>nome1</nome>
                        <duracao>0:47</duracao>
                    </obra>
                </obras>
                <musicos>
                    <musico tipo="professor" id="P1">
                        <nome>nome2</nome>
                        <instrumento>I22</instrumento>
                    </musico>
                    <musico tipo="aluno" id="A1510">
                        <nome>nome3</nome>
                        <instrumento>I2</instrumento>
                    </musico>
                </musicos>
            </atuacao>
            <atuacao tipo="solo">
                <hora_inicio>12:30</hora_inicio>
                <obras>
                    <obra id="O1">
                        <nome>nome0</nome>
                        <duracao>0:20</duracao>
                    </obra>
                    <obra id="O23">
                        <nome>nome1</nome>
                        <duracao>0:47</duracao>
                    </obra>
                </obras>
                <musicos>
                    <musico tipo="aluno" id="A1510">
                        <nome>nome2</nome>
                        <instrumento>I22</instrumento>
                    </musico>
                </musicos>
            </atuacao>
        </atuacoes>
    </audicao>
</audicoes>
